import os

# Kafka InfluxDB Consumer Configuration
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka-broker:9092")
KAFKA_INFLUXDB_TAXI_DATA_CONSUMER_TOPIC = os.getenv("KAFKA_INFLUXDB_TAXI_DATA_CONSUMER_TOPIC", "taxi.processed_data.stream")
KAFKA_INFLUXDB_TAXI_DATA_CONSUMER_GROUP = os.getenv("KAFKA_INFLUXDB_TAXI_DATA_CONSUMER_GROUP", "influx_taxi_data_consumer_group")
KAFKA_INFLUXDB_TAXI_VIOLATION_ALERTS_CONSUMER_TOPIC = os.getenv("KAFKA_INFLUXDB_TAXI_VIOLATION_ALERTS_CONSUMER_TOPIC", "taxi.violation_alerts.stream")
KAFKA_INFLUXDB_TAXI_VIOLATION_ALERTS_CONSUMER_GROUP = os.getenv("KAFKA_INFLUXDB_TAXI_VIOLATION_ALERTS_CONSUMER_GROUP", "influx_taxi_violation_alerts_consumer_group")
KAFKA_INFLUXDB_TAXI_FLEET_METRICS_CONSUMER_TOPIC = os.getenv("KAFKA_INFLUXDB_TAXI_FLEET_METRICS_CONSUMER_TOPIC", "taxi.fleet_metrics.stream")
KAFKA_INFLUXDB_TAXI_FLEET_METRICS_CONSUMER_GROUP = os.getenv("KAFKA_INFLUXDB_TAXI_FLEET_METRICS_CONSUMER_GROUP", "influx_taxi_fleet_metrics_consumer_group")
KAFKA_INFLUXDB_CONSUMER_STARTUP_DELAY = int(os.getenv("KAFKA_INFLUXDB_CONSUMER_STARTUP_DELAY", 10))

# InfluxDB Configuration
INFLUXDB_URL = os.getenv("INFLUXDB_URL", "http://localhost:8086")
INFLUXDB_TOKEN = os.getenv("DOCKER_INFLUXDB_INIT_ADMIN_TOKEN")
INFLUXDB_ORG = os.getenv("DOCKER_INFLUXDB_INIT_ORG")
INFLUXDB_BUCKET = os.getenv("DOCKER_INFLUXDB_INIT_BUCKET")
