import os

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
KAFKA_CONSUMER_STARTUP_DELAY = int(os.getenv("KAFKA_REDIS_CONSUMER_STARTUP_DELAY", 10))
KAFKA_REDIS_TAXI_DATA_CONSUMER_TOPIC = os.getenv("KAFKA_REDIS_TAXI_DATA_CONSUMER_TOPIC", "taxi.processed_data.stream")
KAFKA_REDIS_TAXI_DATA_CONSUMER_GROUP = os.getenv("KAFKA_REDIS_TAXI_DATA_CONSUMER_GROUP", "redis_taxi_data_consumer_group")
KAFKA_REDIS_TAXI_VIOLATION_ALERTS_CONSUMER_TOPIC = os.getenv("KAFKA_REDIS_TAXI_VIOLATION_ALERTS_CONSUMER_TOPIC", "taxi.violation_alerts.stream")
KAFKA_REDIS_TAXI_VIOLATION_ALERTS_CONSUMER_GROUP = os.getenv("KAFKA_REDIS_TAXI_VIOLATION_ALERTS_CONSUMER_GROUP", "redis_taxi_violation_alerts_consumer_group")
KAFKA_REDIS_TAXI_FLEET_METRICS_CONSUMER_TOPIC = os.getenv("KAFKA_REDIS_TAXI_FLEET_METRICS_CONSUMER_TOPIC", "taxi.fleet_metrics.stream")
KAFKA_REDIS_TAXI_FLEET_METRICS_CONSUMER_GROUP = os.getenv("KAFKA_REDIS_TAXI_FLEET_METRICS_CONSUMER_GROUP", "redis_taxi_fleet_metrics_consumer_group")
BATCH_INTERVAL_IN_SECONDS = int(os.getenv("KAFKA_REDIS_CONSUMER_BATCH_INTERVAL_IN_SECONDS", 1))
BATCH_SIZE_LIMIT = int(os.getenv("KAFKA_REDIS_CONSUMER_BATCH_SIZE_LIMIT", 500))
ASYNCIO_QUEUE_SIZE_LIMIT = int(os.getenv("KAFKA_REDIS_CONSUMER_ASYNCIO_QUEUE_SIZE_LIMIT", 1000))

REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
REDIS_DB = int(os.getenv("REDIS_DB", 0))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", None)
REDIS_TAXI_VIOLATION_ALERTS_STREAM = os.getenv("REDIS_TAXI_VIOLATION_ALERTS_STREAM", "taxi_violation_alerts")
